=== aravindsarma/springIntoFitness/springfit/src/test/resources/dailyReportIn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.jstartpro.com/dailyReportIn"
	xmlns:repIn="http://www.jstartpro.com/dailyReportIn"
	elementFormDefault="unqualified">

	<element name="report" type="repIn:Report"></element>

	<complexType name="Report">
		<sequence>
			<element name="date" type="date" />
			<element name="team" type="repIn:Team" maxOccurs="3" />
		</sequence>
	</complexType>

	<complexType name="Team">
		<sequence>
			<element name="teamName" type="repIn:TeamName" />
			<element name="player" type="repIn:Player" maxOccurs="3" />
		</sequence>
	</complexType>

	<complexType name="Player">
		<sequence>
			<element name="name" type="repIn:String45Chars" />
			<element name="cardio" type="int" />
			<element name="strength" type="int" />
		</sequence>
	</complexType>

	<simpleType name="TeamName">
		<restriction base="string">
			<enumeration value="Lean Men A" />
			<enumeration value="Lean Men B" />
			<enumeration value="Lean Men C" />
		</restriction>
	</simpleType>

	<simpleType name="String45Chars">
		<restriction base="string">
			<maxLength value="45"></maxLength>
		</restriction>
	</simpleType>
</schema>

=== aravindsarma/springIntoFitness/springfit/dailyEntry_2016-4-8.xml
<?xml version="1.0" encoding="UTF-8"?>
<repIn:report xmlns:repIn="http://www.jstartpro.com/dailyReportIn"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jstartpro.com/dailyReportIn dailyReportIn.xsd ">
	<date>2016-04-08</date>
	<team>
		<teamName>Lean Men A</teamName>
		<player>
			<name>Aravind</name>
			<cardio>3</cardio>
			<strength>2</strength>
		</player>
		<player>
			<name>Adam</name>
			<cardio>3</cardio>
			<strength>4</strength>
		</player>
		<player>
			<name>Tom</name>
			<cardio>4</cardio>
			<strength>0</strength>
		</player>
	</team>
	<team>
		<teamName>Lean Men B</teamName>
		<player>
			<name>Greg</name>
			<cardio>0</cardio>
			<strength>0</strength>
		</player>
		<player>
			<name>Bhushan</name>
			<cardio>0</cardio>
			<strength>0</strength>
		</player>
		<player>
			<name>Andy</name>
			<cardio>3</cardio>
			<strength>2</strength>
		</player>
	</team>
	<team>
		<teamName>Lean Men C</teamName>
		<player>
			<name>Sakthi</name>
			<cardio>0</cardio>
			<strength>0</strength>
		</player>
		<player>
			<name>Doug</name>
			<cardio>4</cardio>
			<strength>0</strength>
		</player>
		<player>
			<name>Siva</name>
			<cardio>0</cardio>
			<strength>0</strength>
		</player>
	</team>
</repIn:report>
